/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usuario
 */
public class Main extends javax.swing.JFrame {
    Lavavajillas lava = new Lavavajillas();
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        lava.mostrarEstado();
        puerta.setText(lava.getAbierto());
        energia.setText(lava.getEncendido());
        programa.setText(lava.getPrograma());       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abrirPuerta = new javax.swing.JButton();
        cerrarPuerta = new javax.swing.JButton();
        encender = new javax.swing.JButton();
        apagar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        puerta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        energia = new javax.swing.JTextField();
        enjuagado = new javax.swing.JButton();
        prelavado = new javax.swing.JButton();
        lavado = new javax.swing.JButton();
        aclarado = new javax.swing.JButton();
        secado = new javax.swing.JButton();
        avanzar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        programa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        abrirPuerta.setText("Abrir Puerta");
        abrirPuerta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirPuertaActionPerformed(evt);
            }
        });

        cerrarPuerta.setText("Cerrar Puerta");
        cerrarPuerta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarPuertaActionPerformed(evt);
            }
        });

        encender.setText("Encender");
        encender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encenderActionPerformed(evt);
            }
        });

        apagar.setText("Apagar");
        apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarActionPerformed(evt);
            }
        });

        jLabel1.setText("Puerta:");

        puerta.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setText("Energía:");

        enjuagado.setText("Enjuagado");
        enjuagado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enjuagadoActionPerformed(evt);
            }
        });

        prelavado.setText("Prelavado");
        prelavado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prelavadoActionPerformed(evt);
            }
        });

        lavado.setText("Lavado");
        lavado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lavadoActionPerformed(evt);
            }
        });

        aclarado.setText("Aclarado");
        aclarado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aclaradoActionPerformed(evt);
            }
        });

        secado.setText("Secado");
        secado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secadoActionPerformed(evt);
            }
        });

        avanzar.setText("Avanzar estado");
        avanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avanzarActionPerformed(evt);
            }
        });

        jLabel3.setText("Programa:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(encender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(apagar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(avanzar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(programa))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(abrirPuerta)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cerrarPuerta))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(puerta)))
                                .addGap(65, 65, 65)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(energia, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(enjuagado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prelavado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lavado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aclarado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(secado)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(2, 2, 2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abrirPuerta)
                    .addComponent(cerrarPuerta)
                    .addComponent(encender)
                    .addComponent(apagar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(puerta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(energia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enjuagado)
                    .addComponent(prelavado)
                    .addComponent(lavado)
                    .addComponent(aclarado)
                    .addComponent(secado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avanzar)
                    .addComponent(jLabel3)
                    .addComponent(programa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirPuertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirPuertaActionPerformed
        lava.mostrarEstado();
        lava.setAbierto(true);        
        puerta.setText(lava.getAbierto());
    }//GEN-LAST:event_abrirPuertaActionPerformed

    private void cerrarPuertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarPuertaActionPerformed
        lava.mostrarEstado();
        lava.setAbierto(false);    
        puerta.setText(lava.getAbierto());
    }//GEN-LAST:event_cerrarPuertaActionPerformed

    private void encenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encenderActionPerformed
        lava.mostrarEstado();
        lava.setEncendido(true);       
        energia.setText(lava.getEncendido());
    }//GEN-LAST:event_encenderActionPerformed

    private void apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagarActionPerformed
        lava.mostrarEstado();
        lava.setEncendido(false);
        energia.setText(lava.getEncendido());
    }//GEN-LAST:event_apagarActionPerformed

    private void enjuagadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enjuagadoActionPerformed
        lava.setPrograma(Lavavajillas.ENJUAGADO);
        this.programa.setText(lava.getPrograma());
        
    }//GEN-LAST:event_enjuagadoActionPerformed

    private void prelavadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prelavadoActionPerformed
        lava.setPrograma(Lavavajillas.PRELAVADO);
        this.programa.setText(lava.getPrograma());
    }//GEN-LAST:event_prelavadoActionPerformed

    private void lavadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lavadoActionPerformed
         lava.setPrograma(Lavavajillas.LAVADO);
         this.programa.setText(lava.getPrograma());
    }//GEN-LAST:event_lavadoActionPerformed

    private void aclaradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aclaradoActionPerformed
         lava.setPrograma(Lavavajillas.ACLARADO);
         this.programa.setText(lava.getPrograma());
    }//GEN-LAST:event_aclaradoActionPerformed

    private void secadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secadoActionPerformed
         lava.setPrograma(Lavavajillas.SECADO);
         this.programa.setText(lava.getPrograma());
    }//GEN-LAST:event_secadoActionPerformed

    private void avanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avanzarActionPerformed
        lava.avanzarPrograma();
        this.programa.setText(lava.getPrograma());
        this.energia.setText(lava.getEncendido());
    }//GEN-LAST:event_avanzarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirPuerta;
    private javax.swing.JButton aclarado;
    private javax.swing.JButton apagar;
    private javax.swing.JButton avanzar;
    private javax.swing.JButton cerrarPuerta;
    private javax.swing.JButton encender;
    private javax.swing.JTextField energia;
    private javax.swing.JButton enjuagado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton lavado;
    private javax.swing.JButton prelavado;
    private javax.swing.JTextField programa;
    private javax.swing.JTextField puerta;
    private javax.swing.JButton secado;
    // End of variables declaration//GEN-END:variables
}
